"""Add worklog settlement system

Revision ID: 9dfb02898407
Revises: 1a31ce608336
Create Date: 2026-01-28 13:10:09.400422

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9dfb02898407'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remittance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='remittancestatus'), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittance_worker_id'), 'remittance', ['worker_id'], unique=False)
    op.create_table('worklog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_remitted_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remittance_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittance.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worklog_task_id'), 'worklog', ['task_id'], unique=False)
    op.create_index(op.f('ix_worklog_worker_id'), 'worklog', ['worker_id'], unique=False)
    op.create_table('adjustment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worklog_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('type', sa.Enum('DEDUCTION', 'BONUS', 'CORRECTION', name='adjustmenttype'), nullable=False),
    sa.Column('settlement_status', sa.Enum('UNREMITTED', 'REMITTED', name='settlementstatus'), nullable=False),
    sa.Column('remittance_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittance.id'], ),
    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustment_worklog_id'), 'adjustment', ['worklog_id'], unique=False)
    op.create_table('timesegment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worklog_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REMOVED', 'DISPUTED', name='timesegmentstatus'), nullable=False),
    sa.Column('settlement_status', sa.Enum('UNREMITTED', 'REMITTED', name='settlementstatus'), nullable=False),
    sa.Column('remittance_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittance.id'], ),
    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesegment_worklog_id'), 'timesegment', ['worklog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesegment_worklog_id'), table_name='timesegment')
    op.drop_table('timesegment')
    op.drop_index(op.f('ix_adjustment_worklog_id'), table_name='adjustment')
    op.drop_table('adjustment')
    op.drop_index(op.f('ix_worklog_worker_id'), table_name='worklog')
    op.drop_index(op.f('ix_worklog_task_id'), table_name='worklog')
    op.drop_table('worklog')
    op.drop_index(op.f('ix_remittance_worker_id'), table_name='remittance')
    op.drop_table('remittance')
    op.drop_table('task')
    # ### end Alembic commands ###
